apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dezalazar/argocd_kustomize_project.git'
    path: apps/hello-world/overlays/stg
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
