apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/dezalazar/argocd_kustomize_project.git'
        revision: main
        directories:
          - path: 'apps/hello-world/overlays/*'
  template:
    metadata:
      name: 'hello-world-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/dezalazar/argocd_kustomize_project.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
